name: Generate Snake Animation

on:
  schedule: # Runs once a day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Lets you run it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: aciph-eth
          outputs: dist/snake.svg

      - name: Commit and Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/snake.svg"
          message: "Generate contribution snake"
          push: true
